### ISSUE TITLE
Proposal: Add Recipe for Creating Dependabot Configuration File

### ISSUE THREAD

**Issue by gounthar** [jenkinsci/plugin-modernizer-tool#337]
## Background
The "Improve a plugin tutorial" includes a section titled "[Check dependencies](https://www.jenkins.io/doc/developer/tutorial-improve/automate-dependency-update-checks/)" which outlines the process of creating a GitHub Action for Dependabot. This functionality would be a valuable addition to our recipe collection.

## Proposal
We should develop a new recipe that creates a Dependabot configuration file if one does not already exist in the target repository.

## Existing Resources
OpenRewrite currently offers [a recipe](https://docs.openrewrite.org/recipes/github/changedependabotscheduleinterval) for updating an existing Dependabot GitHub action file. While this recipe doesn't create a new file, it could potentially serve as a starting point or reference for our implementation.

## Implementation Considerations
1. **File Creation**: The recipe should check for the existence of a Dependabot configuration file and create one if it's not present.
2. **Configuration Options**: We need to determine what default settings should be included in the generated file.
3. **Customization**: Consider allowing users to specify certain parameters, such as update frequency or target branches.
4. **Integration**: Ensure the new recipe integrates smoothly with our existing modernization workflow.

## Next Steps
1. Review the OpenRewrite recipe to determine if any components can be adapted for our needs.
2. Draft a specification for the new recipe, including its functionality and any customizable options.
3. Implement the recipe and create appropriate test cases.
4. Update documentation to include information about this new recipe and its usage.

We welcome feedback and suggestions on this proposal to ensure it meets the needs of our user community.

### Are you interested in contributing this feature?

Yes, but out of my comfort zone for sure. 🤣

**Comment by jonesbusy** [comment]
Could be done via declarative recipe

```yaml
  - org.openrewrite.text.CreateTextFile:
      fileContents: |
        version: 2
        updates:
        - package-ecosystem: maven
          directory: /
          schedule:
            interval: monthly
        - package-ecosystem: github-actions
          directory: /
          schedule:
            interval: monthly
      relativeFileName: .github/dependabot.yml
      overwriteExisting: false
```
