### ISSUE TITLE
Dealing with recipes that requires configuration parameters

### ISSUE THREAD

**Issue by sridamul** [jenkinsci/plugin-modernizer-tool#58]
### What feature do you want to see added?

Some recipes like [Replacelibrarieswithapiplugin](https://docs.openrewrite.org/recipes/jenkins/replacelibrarieswithapiplugin), [UpgradeJavaVersion](https://docs.openrewrite.org/recipes/jenkins/upgradejavaversion) etc. requires configuration parameters to execute the recipe.

Idea:
We can parse the rewrite.yml file (path can be passed as argument, a new option required) to extract the `name` (added to activeRecipes) and `recipeList` (to add the respective recipeArtifactCoordinates)

For Eg: In below rewrite.xml, we can obtain `com.yourorg.IsJenkinsPluginExample` to activeRecipes and `io.jenkins.plugin-modernizer:plugin-modernizer-core:${project.version}` as an artifact coordinate for `org.openrewrite.jenkins.IsJenkinsPlugin` recipe
```
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.IsJenkinsPluginExample
displayName: Is the project a Jenkins plugin? example
recipeList:
  - org.openrewrite.jenkins.IsJenkinsPlugin:
      version: '[1,)'
```

Testing:
I created a rewrite.yml file inside plugin dir and added the name to activeRecipes. This works fine and the recipe is applied to the plugin successfully.

Need to improvise the idea and also open to any other approaches or suggestions.
